language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t nishant/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true nishant/docker-react-app npm run test

deploy: 
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-us-west-1-470464294751"
  bucket_path: "docker-react-app"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
